name: Simple Workflow

    # This workflow will run when manually triggered
    # You can also trigger this workflow from the Actions tab in your repository.
on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World
        run: echo "Hello, World!"
