name: Cronbased only in dev
run-name: Cronbased only in dev

on:
  push:
  workflow_dispatch:

jobs:
  scheduled-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run scheduled task
        run: echo "This job runs every 2 minutes"
